todoapp/todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('new_entry', views.new_entry, name='new_entry'),
    path('<int:entry_id>/', views.change, name='change'),
    path('<int:entry_id>/status/', views.status, name='status'),
    path('<int:entry_id>/select/', views.select, name='select'),
]


todoapp/todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls'))
]

todoapp/todo/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Entry(models.Model):
    entry_text = models.CharField(max_length=200)
    done = models.BooleanField(default=False, null=False)
    def __str__(self):
        return self.entry_text





todoapp/todo/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse

from .models import Entry

# Create your views here.

def index(request):
    entry_list = Entry.objects.all()
    context = {'entry_list' : entry_list}
    return render(request, 'todo/index.html', context)

def status(request, entry_id):
    entry = get_object_or_404(Entry, pk=entry_id)
    return render(request, 'todo/status.html', {'entry': entry})

def change(request, entry_id):
    entry = get_object_or_404(Entry, pk=entry_id)
    return render(request, 'todo/change.html', {'entry': entry})

def select(request, entry_id):
    entry = get_object_or_404(Entry, pk=entry_id)
    try: 
        done = request.POST['done'] == 'true'
        entry.done = done
        entry.save()
    except (KeyError):
        return render(request, 'todo/change.html', {'entry': entry, 'error':'Bitte Status wählen'})
    else:
        return redirect(reverse('todo:status', args=(entry_id,)))

def new_entry(request):
    entry_text = request.POST["entry_text"]
    Entry.objects.create(entry_text=entry_text)
    return HttpResponseRedirect(reverse('todo:index'))


todoapp/todo/templates/todo/change.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<div class='container-fluid'>
<h1>Detailansicht</h1>
<h2>Status ändern</h2>

{% if error %}<p class="p-3 mb-2 bg-danger text-white">{{ error }}</p>{% endif %}

<form action="{% url 'todo:select' entry.id %}" method="post">
{% csrf_token %}

<input type="radio" name="done" id="donetrue" value="true">
<label for="donetrue">Erledigt</label><br>

<input type="radio" name="done" id="donefalse" value="false">
<label for="donefalse">Ausstehend</label><br>

<input type="submit" value="Ändern" class="p-3 mb-2 bg-info text-white">
</form>
</div>

todoapp/todo/templates/todo/index.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<div class='container-fluid'>
<h1>ToDo-Liste</h1></br>

{% if entry_list %}
    <ol>
    {% for entry in entry_list %}
    <li><a href="/todo/{{entry.id}}", class="text-dark">{{ entry }}</a></br>
        {% if entry.done %}
            <p class="text-success">Erledigt
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
            </svg>
            </p>
        {% else %}
            <p class="text-danger">Ausstehend
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path fill-rule="evenodd" d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z"/>
            </svg>
            </p>
        {% endif %}</br>
    </li>
    {% endfor %}
    </ol>
    <form action="{% url 'todo:new_entry' %}" method="post">
        {% csrf_token %}
        <input type="text" name="entry_text" placeholder='Name'>
        <input type="submit" class="p-3 mb-2 bg-info text-white" value="Anlegen">
    </form>
{% else %}
    <p>No ToDo's.</p>
{% endif %}
</div>

todoapp/todo/templates/todo/status.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<div class='container-fluid'>
<h1>Status erfolgreich geändert</h1>

{% if entry.done %}
    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
    </svg>
    Erledigt</br></br>
{% else %}
    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
    <path fill-rule="evenodd" d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z"/>
    </svg>
    Ausstehend</br></br>
{% endif %}


<a href="/todo/" class="p-3 mb-2 bg-info text-white">Zurück zur ToDo-Liste?</a>
<a href="/todo/{{entry.id}}" class="p-3 mb-2 bg-info text-white">Status erneut ändern?</a>
</div>